### ISSUE TITLE
Sending payload fail at offset 61440

### ISSUE THREAD

**Issue by devmehta912** [DavidBuchanan314/NXLoader#10]
I am using it on s8 but not able to send the payload. Is it a problem for everyone on s8? And any fix

**Comment by DavidBuchanan314** [comment]
Works for most people on s8, try a different cable.

**Comment by TheRealBensis** [comment]
I have the same problem, I have tried different cables

**Comment by robbeofficial** [comment]
Got the exact same error on the s8 and can confirm that it is NOT the cable (using the same cable with ReSwitched's Fusee Launcher on PC). Consider reopening the issue! I am sure a fix can be found.

**Comment by flamel1292** [comment]
Samsung Galaxy S9+ using the cable and the OTG adapter that came with the device.

**Comment by lsevero** [comment]
Got the exact same error, with different cables and payloads.

**Comment by DavidBuchanan314** [comment]
@robbeofficial If it's not the cable, it's likely something fairly deep within the USB device drivers that's causing the issue. I'm not a driver developer, so there's not much I can do.

**Comment by ebiak** [comment]
So I used to have a note 3 and that injected the payloads easily then I switched to a Samsung galaxy a70 and it didn't work anymore
