### ISSUE TITLE
sending payload failed at offset 65536

### ISSUE THREAD

**Issue by leboman** [DavidBuchanan314/NXLoader#16]
Hi - I keep getting this error.

Any ideas anybody?? It was working perfectly a week ago.

Please see picture below. 
![screenshot_20180619-175554](https://user-images.githubusercontent.com/24217790/41584578-ff3d4684-73ea-11e8-8a03-e771f2cfcc61.jpg)

**Comment by DavidBuchanan314** [comment]
The code hasn't changed in the last week, so clearly you have a bad USB cable.

**Comment by leboman** [comment]
Wow you are f****ng useless. I tried 4 different cables so clearly your 'first Android app' is a piece of cow shit.

**Comment by a7mag3ddon** [comment]
App works fine, been using it since it launched without. Issues.
