### ISSUE TITLE
Possibility to define two Payloads from wich can be Choosen once the USB Cable is connected.

### ISSUE THREAD

**Issue by NightHammer1000** [DavidBuchanan314/NXLoader#18]
It would be nice if we could define two Payloads.
For Example SX OS and hekate.

And once you connect the Switch to your Phone a Popup appears and asks you wich Payload to sent.

**Comment by DavidBuchanan314** [comment]
I appreciate the suggestion, but I think this would be too much effort to implement for a relatively niche scenario.

Requiring a popup would break the "works when your phone is locked" use case.
