### ISSUE TITLE
One plus 5t not working OTG

### ISSUE THREAD

**Issue by cloudstrife999** [DavidBuchanan314/NXLoader#27]
It's not working with one plus 5t stock ROM otg enabled.

**Comment by MenosGrante** [comment]
Have you enabled OTG Storage in Settings?

**Comment by cloudstrife999** [comment]
Yes I have. Still no luck.

**Comment by matotim** [comment]
Just tried it myself, and everything's working correctly from my OnePlus 5T

**Comment by cloudstrife999** [comment]
Strange. It has started working, once  I connected USB OTG adapter to my phone and cable to switch. Now working perfectly. Thanks.
