### ISSUE TITLE
Verizon Moto z2 Force

### ISSUE THREAD

**Issue by laramie14** [DavidBuchanan314/NXLoader#7]
When I open the app, it does not request app permissions at all, I cleared cache, data, reinstalled, manually configured usb auth, and have debug setting enabled. Using a c-c cable

**Comment by DavidBuchanan314** [comment]
Your OS is responsible for presenting the permissions dialog. It should appear when the switch is connected.

If it doesn't show, something is wrong with your OS and I can't really help you there :man_shrugging:

**Comment by Reisyukaku** [comment]
I looked into it and I think the issue is that libusb refers to the usb devices through /dev/bus/usb/*
But on my stock Oreo rom, it doesn't seem to use that system. Not sure if that's something that can be changed in the kernel config or not though.

**Comment by DavidBuchanan314** [comment]
That path never gets used for anything, it's just printed for debugging, from `device.getDeviceName()`.
